-- colors.lua (Auto-generated by Matugen)
local colors = {
  bg0     = "{{colors.background.default.hex_stripped}}",
  bg1     = "{{colors.surface_container_low.default.hex_stripped}}",
  bg2     = "{{colors.surface_container.default.hex_stripped}}",
  bg3     = "{{colors.surface_container_high.default.hex_stripped}}",
  fg1     = "{{colors.on_surface.default.hex_stripped}}",
  primary = "{{colors.primary.default.hex_stripped}}",
  secondary = "{{colors.secondary.default.hex_stripped}}",
  tertiary = "{{colors.tertiary.default.hex_stripped}}",
  gray    = "{{colors.outline.default.hex_stripped}}",
  silver  = "{{colors.outline_variant.default.hex_stripped}}",
  red     = "{{colors.error.default.hex_stripped}}",
  green   = "{{colors.tertiary.default.hex_stripped}}",
  yellow  = "{{colors.primary_container.default.hex_stripped}}",
  blue    = "{{colors.primary.default.hex_stripped}}",
  purple  = "{{colors.secondary.default.hex_stripped}}",
  aqua    = "{{colors.secondary_container.default.hex_stripped}}",
  orange  = "{{colors.tertiary_container.default.hex_stripped}}",
}
return colors
