pragma Singleton
import QtQuick

QtObject {
    // Auto-generated by Matugen from active wallpaper
    readonly property color bg0: "{{colors.background.default.hex}}"
    readonly property color bg1: "{{colors.surface_container_low.default.hex}}"
    readonly property color bg2: "{{colors.surface_container.default.hex}}"
    readonly property color bg3: "{{colors.surface_container_high.default.hex}}"
    readonly property color fg1: "{{colors.on_surface.default.hex}}"
    readonly property color fg0: "{{colors.on_surface.default.hex}}"
    readonly property color gray: "{{colors.outline.default.hex}}"
    readonly property color silver: "{{colors.outline_variant.default.hex}}"
    readonly property color accent: "{{colors.primary.default.hex}}"
    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color red: "{{colors.error.default.hex}}"
}
