-- ~/.config/nvim/lua/colors.lua
-- Auto-generated by Theme Engine
local M = {
  bg0 = "#1a1111",
  bg1 = "#22191a",
  bg2 = "#271d1e",
  bg3 = "#322828",
  fg1 = "#f0dede",
  fg0 = "#f0dede",
  gray = "#9f8c8c",
  silver = "#524343",
  accent = "#ffb3b6",
  primary = "#ffb3b6",
  secondary = "#e6bdbe",
  tertiary = "#e7c08d",
  red = "#ffb4ab",
}

local hl = vim.api.nvim_set_hl
hl(0, "Normal", { bg = M.bg0, fg = M.fg1 })
hl(0, "NormalFloat", { bg = M.bg1, fg = M.fg1 })
hl(0, "FloatBorder", { bg = M.bg1, fg = M.accent })
hl(0, "CursorLine", { bg = M.bg1 })
hl(0, "LineNr", { fg = M.gray })
hl(0, "CursorLineNr", { fg = M.accent, bold = true })
hl(0, "StatusLine", { bg = M.bg1, fg = M.fg1 })
hl(0, "StatusLineNC", { bg = M.bg0, fg = M.gray })
hl(0, "Pmenu", { bg = M.bg1, fg = M.fg1 })
hl(0, "PmenuSel", { bg = M.accent, fg = M.bg0 })
hl(0, "Visual", { bg = M.bg2 })
hl(0, "SignColumn", { bg = M.bg0 })

return M
