-- ~/.config/nvim/lua/colors.lua
-- Auto-generated by Theme Engine
local M = {
  bg0 = "#0b0c10",
  bg1 = "#121318",
  bg2 = "#181a20",
  bg3 = "#22242c",
  fg1 = "#f9ddd3",
  fg0 = "#f9ddd3",
  gray = "#a38c83",
  silver = "#55433c",
  accent = "#ffb598",
  primary = "#ffb598",
  secondary = "#f0bc95",
  tertiary = "#efbe79",
  red = "#ffb4ab",
}

local hl = vim.api.nvim_set_hl
hl(0, "Normal", { bg = M.bg0, fg = M.fg1 })
hl(0, "NormalFloat", { bg = M.bg1, fg = M.fg1 })
hl(0, "FloatBorder", { bg = M.bg1, fg = M.accent })
hl(0, "CursorLine", { bg = M.bg1 })
hl(0, "LineNr", { fg = M.gray })
hl(0, "CursorLineNr", { fg = M.accent, bold = true })
hl(0, "StatusLine", { bg = M.bg1, fg = M.fg1 })
hl(0, "StatusLineNC", { bg = M.bg0, fg = M.gray })
hl(0, "Pmenu", { bg = M.bg1, fg = M.fg1 })
hl(0, "PmenuSel", { bg = M.accent, fg = M.bg0 })
hl(0, "Visual", { bg = M.bg2 })
hl(0, "SignColumn", { bg = M.bg0 })

return M
