-- colors.lua (Auto-generated by Matugen)
local colors = {
  bg0     = "1e100e",
  bg1     = "271816",
  bg2     = "2b1c19",
  bg3     = "372623",
  fg1     = "f9dcd8",
  primary = "ffb4a9",
  secondary = "f4ba9e",
  tertiary = "f9ba80",
  gray    = "a38b88",
  silver  = "55423f",
  red     = "ffb4ab",
  green   = "f9ba80",
  yellow  = "930003",
  blue    = "ffb4a9",
  purple  = "f4ba9e",
  aqua    = "653d28",
  orange  = "683d0e",
}
return colors
