-- colors.lua (Auto-generated by Theme Engine)
local colors = {
  bg0     = "0b0c10",
  bg1     = "121318",
  bg2     = "181a20",
  bg3     = "22242c",
  fg1     = "f9ddd3",
  primary = "ffb598",
  secondary = "f0bc95",
  tertiary = "efbe79",
  gray    = "a38c83",
  silver  = "55433c",
  red     = "ffb4ab",
  green   = "efbe79",
  yellow  = "7f2b00",
  blue    = "ffb598",
  purple  = "f0bc95",
  aqua    = "623f21",
  orange  = "614004",
}
return colors
